---
- name: ADD SNMP FILE & ASSEMBLY
  template: src=snmp.j2 dest={{ inventory_dir }}/{{ build_dir }}/03-snmp.conf
  run_once: true 
  tags: ['snmp_file']


- name: SETUP HOST  SNMP
  ios_config:
      authorize: yes 
      provider: "{{ ios_provider }}"
      diff_against: running
      src: snmp.j2 
  tags: ['snmp']

...
