---
- name: DEPLOY CONFIG TO SITES
  hosts: all
  gather_facts: no 
  connection: local  


  tasks:
      - name: PREPARE HOSTS FOLDER
        include: ./playbooks/prep_infra.yml 
        tags: ['prep']

      - name: GATTER HOSTS FACT
        include: ./playbooks/get_facts_napalm.yml 
        tags: ['getterfacts']

- import_playbook: ./playbooks/ios_push.yml 
  tags: ['push']

#      - name: PUSH CONFIG TO HOSTS
#        import_playbook: ./playbooks/ios_push.yml 
#        tags: ['push']
#
...
