get_facts:
    napalm_facts:
        fqdn: SW_Noc_Automacao(48PoE).victoria.local
        hostname: SW_Noc_Automacao(48PoE)
        interface_list:
        - Vlan1
        - Vlan99
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - FastEthernet0/25
        - FastEthernet0/26
        - FastEthernet0/27
        - FastEthernet0/28
        - FastEthernet0/29
        - FastEthernet0/30
        - FastEthernet0/31
        - FastEthernet0/32
        - FastEthernet0/33
        - FastEthernet0/34
        - FastEthernet0/35
        - FastEthernet0/36
        - FastEthernet0/37
        - FastEthernet0/38
        - FastEthernet0/39
        - FastEthernet0/40
        - FastEthernet0/41
        - FastEthernet0/42
        - FastEthernet0/43
        - FastEthernet0/44
        - FastEthernet0/45
        - FastEthernet0/46
        - FastEthernet0/47
        - FastEthernet0/48
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        - GigabitEthernet0/3
        - GigabitEthernet0/4
        model: WS-C2960-48PST-L
        os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
            SOFTWARE (fc1)
        serial_number: FOC1412W2LH
        uptime: 20653020
        vendor: Cisco
    napalm_fqdn: SW_Noc_Automacao(48PoE).victoria.local
    napalm_hostname: SW_Noc_Automacao(48PoE)
    napalm_interface_list:
    - Vlan1
    - Vlan99
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - FastEthernet0/25
    - FastEthernet0/26
    - FastEthernet0/27
    - FastEthernet0/28
    - FastEthernet0/29
    - FastEthernet0/30
    - FastEthernet0/31
    - FastEthernet0/32
    - FastEthernet0/33
    - FastEthernet0/34
    - FastEthernet0/35
    - FastEthernet0/36
    - FastEthernet0/37
    - FastEthernet0/38
    - FastEthernet0/39
    - FastEthernet0/40
    - FastEthernet0/41
    - FastEthernet0/42
    - FastEthernet0/43
    - FastEthernet0/44
    - FastEthernet0/45
    - FastEthernet0/46
    - FastEthernet0/47
    - FastEthernet0/48
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    - GigabitEthernet0/3
    - GigabitEthernet0/4
    napalm_interfaces:
        FastEthernet0/1:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:81
            speed: 100
        FastEthernet0/10:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:8A
            speed: 100
        FastEthernet0/11:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:8B
            speed: 100
        FastEthernet0/12:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:8C
            speed: 100
        FastEthernet0/13:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:8D
            speed: 100
        FastEthernet0/14:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:8E
            speed: 100
        FastEthernet0/15:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:8F
            speed: 10
        FastEthernet0/16:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:90
            speed: 100
        FastEthernet0/17:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:91
            speed: 10
        FastEthernet0/18:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:92
            speed: 10
        FastEthernet0/19:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:93
            speed: 10
        FastEthernet0/2:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:82
            speed: 10
        FastEthernet0/20:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:94
            speed: 10
        FastEthernet0/21:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:95
            speed: 10
        FastEthernet0/22:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:96
            speed: 10
        FastEthernet0/23:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:97
            speed: 10
        FastEthernet0/24:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:98
            speed: 10
        FastEthernet0/25:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:99
            speed: 10
        FastEthernet0/26:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:9A
            speed: 10
        FastEthernet0/27:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:9B
            speed: 10
        FastEthernet0/28:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:9C
            speed: 10
        FastEthernet0/29:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:9D
            speed: 10
        FastEthernet0/3:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:83
            speed: 100
        FastEthernet0/30:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:9E
            speed: 10
        FastEthernet0/31:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:9F
            speed: 10
        FastEthernet0/32:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A0
            speed: 10
        FastEthernet0/33:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A1
            speed: 10
        FastEthernet0/34:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A2
            speed: 10
        FastEthernet0/35:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A3
            speed: 10
        FastEthernet0/36:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A4
            speed: 10
        FastEthernet0/37:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A5
            speed: 10
        FastEthernet0/38:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A6
            speed: 10
        FastEthernet0/39:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A7
            speed: 10
        FastEthernet0/4:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:84
            speed: 10
        FastEthernet0/40:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A8
            speed: 10
        FastEthernet0/41:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:A9
            speed: 10
        FastEthernet0/42:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:AA
            speed: 10
        FastEthernet0/43:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:AB
            speed: 10
        FastEthernet0/44:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:AC
            speed: 10
        FastEthernet0/45:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:AD
            speed: 10
        FastEthernet0/46:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:AE
            speed: 10
        FastEthernet0/47:
            description: Reserved VLAN CCTV
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:AF
            speed: 100
        FastEthernet0/48:
            description: Reserved VLAN CCTV
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:B0
            speed: 100
        FastEthernet0/5:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:85
            speed: 100
        FastEthernet0/6:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:86
            speed: 100
        FastEthernet0/7:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:87
            speed: 100
        FastEthernet0/8:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:88
            speed: 100
        FastEthernet0/9:
            description: CARLOS ROQUE
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:89
            speed: 100
        GigabitEthernet0/1:
            description: G2/0/1.Core
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:B1
            speed: 10
        GigabitEthernet0/2:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:B2
            speed: 1000
        GigabitEthernet0/3:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:B3
            speed: 10
        GigabitEthernet0/4:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:B4
            speed: 10
        Vlan1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:C0
            speed: 1000
        Vlan99:
            description: Network_Management
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 28:93:FE:7C:DB:C1
            speed: 1000
    napalm_interfaces_ip:
        Vlan99:
            ipv4:
                10.80.99.249:
                    prefix_length: 24
    napalm_model: WS-C2960-48PST-L
    napalm_os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FOC1412W2LH
    napalm_uptime: 20653020
    napalm_vendor: Cisco
changed: false
failed: false
