get_facts:
    napalm_facts:
        fqdn: SW24FnDPoE_ARMAZ.PECAS.victoria.local
        hostname: SW24FnDPoE_ARMAZ.PECAS
        interface_list:
        - Vlan1
        - Vlan199
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        model: WS-C2960-24PC-L
        os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
            SOFTWARE (fc1)
        serial_number: FOC1415Z36A
        uptime: 21087060
        vendor: Cisco
    napalm_fqdn: SW24FnDPoE_ARMAZ.PECAS.victoria.local
    napalm_hostname: SW24FnDPoE_ARMAZ.PECAS
    napalm_interface_list:
    - Vlan1
    - Vlan199
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    napalm_interfaces:
        FastEthernet0/1:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:81
            speed: 10
        FastEthernet0/10:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:8A
            speed: 100
        FastEthernet0/11:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:8B
            speed: 100
        FastEthernet0/12:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:8C
            speed: 10
        FastEthernet0/13:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:8D
            speed: 100
        FastEthernet0/14:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:8E
            speed: 100
        FastEthernet0/15:
            description: Reserved Control Magnetico
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:8F
            speed: 10
        FastEthernet0/16:
            description: Reserved Control Magnetico
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:90
            speed: 100
        FastEthernet0/17:
            description: Reserved Control Magnetico
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:91
            speed: 100
        FastEthernet0/18:
            description: Reserved Control Magnetico
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:92
            speed: 10
        FastEthernet0/19:
            description: Reserved Control Magnetico
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:93
            speed: 100
        FastEthernet0/2:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:82
            speed: 100
        FastEthernet0/20:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:94
            speed: 100
        FastEthernet0/21:
            description: RESERVED ACCESS CONTROL
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:95
            speed: 100
        FastEthernet0/22:
            description: LINK-RESERVED-TO-LWAPP
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:96
            speed: 10
        FastEthernet0/23:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:97
            speed: 10
        FastEthernet0/24:
            description: FAST-PORT-TRUNK
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:98
            speed: 10
        FastEthernet0/3:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:83
            speed: 100
        FastEthernet0/4:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:84
            speed: 10
        FastEthernet0/5:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:85
            speed: 100
        FastEthernet0/6:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:86
            speed: 100
        FastEthernet0/7:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:87
            speed: 100
        FastEthernet0/8:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:88
            speed: 100
        FastEthernet0/9:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:89
            speed: 100
        GigabitEthernet0/1:
            description: FAST-PORT-TRUNK
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:99
            speed: 1000
        GigabitEthernet0/2:
            description: FAST-PORT-TRUNK
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:9A
            speed: 10
        Vlan1:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:C0
            speed: 1000
        Vlan199:
            description: VLAN MANAGEMENT
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 1C:17:D3:4D:17:C1
            speed: 1000
    napalm_interfaces_ip:
        Vlan199:
            ipv4:
                10.15.99.15:
                    prefix_length: 24
    napalm_model: WS-C2960-24PC-L
    napalm_os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FOC1415Z36A
    napalm_uptime: 21087060
    napalm_vendor: Cisco
changed: false
failed: false
