get_facts:
    napalm_facts:
        fqdn: CobswBIOmetrico2.victoria.local
        hostname: CobswBIOmetrico2
        interface_list:
        - Vlan1
        - Vlan20
        - Vlan99
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        model: WS-C2960-24LC-S
        os_version: C2960 Software (C2960-LANLITEK9-M), Version 12.2(55)SE7, RELEASE
            SOFTWARE (fc1)
        serial_number: FCQ1714X4VS
        uptime: 17400
        vendor: Cisco
    napalm_fqdn: CobswBIOmetrico2.victoria.local
    napalm_hostname: CobswBIOmetrico2
    napalm_interface_list:
    - Vlan1
    - Vlan20
    - Vlan99
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    napalm_interfaces:
        FastEthernet0/1:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:01
            speed: 100
        FastEthernet0/10:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:0A
            speed: 10
        FastEthernet0/11:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:0B
            speed: 100
        FastEthernet0/12:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:0C
            speed: 10
        FastEthernet0/13:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:0D
            speed: 10
        FastEthernet0/14:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:0E
            speed: 10
        FastEthernet0/15:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:0F
            speed: 10
        FastEthernet0/16:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:10
            speed: 10
        FastEthernet0/17:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:11
            speed: 10
        FastEthernet0/18:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:12
            speed: 10
        FastEthernet0/19:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:13
            speed: 10
        FastEthernet0/2:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:02
            speed: 100
        FastEthernet0/20:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:14
            speed: 10
        FastEthernet0/21:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:15
            speed: 10
        FastEthernet0/22:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:16
            speed: 10
        FastEthernet0/23:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:17
            speed: 10
        FastEthernet0/24:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:18
            speed: 10
        FastEthernet0/3:
            description: Reserved_CCTV
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:03
            speed: 100
        FastEthernet0/4:
            description: Reserved_CCTV
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:04
            speed: 10
        FastEthernet0/5:
            description: Reserved_CCTV
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:05
            speed: 100
        FastEthernet0/6:
            description: Reserved_CCTV
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:06
            speed: 10
        FastEthernet0/7:
            description: Reserved_CCTV
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:07
            speed: 10
        FastEthernet0/8:
            description: Reserved_CCTV
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:08
            speed: 10
        FastEthernet0/9:
            description: RESERVED_END_USER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:09
            speed: 10
        GigabitEthernet0/1:
            description: RESERVDE_TO_TRUNK
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:19
            speed: 1000
        GigabitEthernet0/2:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:1A
            speed: 10
        Vlan1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:40
            speed: 1000
        Vlan20:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:41
            speed: 1000
        Vlan99:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:E2:E2:42
            speed: 1000
    napalm_interfaces_ip:
        Vlan99:
            ipv4:
                10.40.99.26:
                    prefix_length: 24
    napalm_model: WS-C2960-24LC-S
    napalm_os_version: C2960 Software (C2960-LANLITEK9-M), Version 12.2(55)SE7, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FCQ1714X4VS
    napalm_uptime: 17400
    napalm_vendor: Cisco
changed: false
failed: false
