---
ios_provider:
    username: "{{ secret.username }}"
    password: "{{ secret.password }}"
    authorize: true 
    auth_pass: "{{ secret.password }}"
    host: "{{ inventory_hostname }}"


netflow:
    exporters: 
        - { name: "CiscoPrime_Export",
            ip: "10.30.99.252",
            port: "9996",
          }

        - {
            name: "CiscoPrime_Export2",
            ip: "10.30.99.251",
            port: "9991",
          }
    policy: "perform_policy"
    monitor_name: "CiscoPrime_flow"
    record: "MYRECORD"
      

...
