get_facts:
    napalm_facts:
        fqdn: Modus_SW7st_FLOOR1.victoria.local
        hostname: Modus_SW7st_FLOOR1
        interface_list:
        - Vlan1
        - Vlan99
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        model: WS-C2960-24PC-L
        os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE7, RELEASE
            SOFTWARE (fc1)
        serial_number: FCQ1713X2D2
        uptime: 21415500
        vendor: Cisco
    napalm_fqdn: Modus_SW7st_FLOOR1.victoria.local
    napalm_hostname: Modus_SW7st_FLOOR1
    napalm_interface_list:
    - Vlan1
    - Vlan99
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    napalm_interfaces:
        FastEthernet0/1:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:01
            speed: 100
        FastEthernet0/10:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:0A
            speed: 100
        FastEthernet0/11:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:0B
            speed: 100
        FastEthernet0/12:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:0C
            speed: 10
        FastEthernet0/13:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:0D
            speed: 10
        FastEthernet0/14:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:0E
            speed: 10
        FastEthernet0/15:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:0F
            speed: 100
        FastEthernet0/16:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:10
            speed: 10
        FastEthernet0/17:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:11
            speed: 10
        FastEthernet0/18:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:12
            speed: 10
        FastEthernet0/19:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:13
            speed: 10
        FastEthernet0/2:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:02
            speed: 10
        FastEthernet0/20:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:14
            speed: 100
        FastEthernet0/21:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:15
            speed: 10
        FastEthernet0/22:
            description: RESERVED AP-CAPWAP
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:16
            speed: 100
        FastEthernet0/23:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:17
            speed: 10
        FastEthernet0/24:
            description: Reserved trunk
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:18
            speed: 100
        FastEthernet0/3:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:03
            speed: 100
        FastEthernet0/4:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:04
            speed: 10
        FastEthernet0/5:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:05
            speed: 10
        FastEthernet0/6:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:06
            speed: 100
        FastEthernet0/7:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:07
            speed: 100
        FastEthernet0/8:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:08
            speed: 100
        FastEthernet0/9:
            description: RESERVED END USER (POE)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:09
            speed: 100
        GigabitEthernet0/1:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:19
            speed: 10
        GigabitEthernet0/2:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:1A
            speed: 10
        Vlan1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:40
            speed: 1000
        Vlan99:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 44:AD:D9:3F:CA:41
            speed: 1000
    napalm_interfaces_ip:
        Vlan99:
            ipv4:
                10.31.99.4:
                    prefix_length: 24
    napalm_model: WS-C2960-24PC-L
    napalm_os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE7, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FCQ1713X2D2
    napalm_uptime: 21415500
    napalm_vendor: Cisco
changed: false
failed: false
