get_facts:
    napalm_facts:
        fqdn: SW24FnDPoE_SERV.ROOM.1.victoria.local
        hostname: SW24FnDPoE_SERV.ROOM.1
        interface_list:
        - Vlan1
        - Vlan2
        - Vlan199
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        - Port-channel1
        model: WS-C2960-24PC-L
        os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
            SOFTWARE (fc1)
        serial_number: FOC1326Z51S
        uptime: 6250860
        vendor: Cisco
    napalm_fqdn: SW24FnDPoE_SERV.ROOM.1.victoria.local
    napalm_hostname: SW24FnDPoE_SERV.ROOM.1
    napalm_interface_list:
    - Vlan1
    - Vlan2
    - Vlan199
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    - Port-channel1
    napalm_interfaces:
        FastEthernet0/1:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:01
            speed: 10
        FastEthernet0/10:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:0A
            speed: 100
        FastEthernet0/11:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:0B
            speed: 100
        FastEthernet0/12:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:0C
            speed: 100
        FastEthernet0/13:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:0D
            speed: 100
        FastEthernet0/14:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:0E
            speed: 100
        FastEthernet0/15:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:0F
            speed: 10
        FastEthernet0/16:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:10
            speed: 10
        FastEthernet0/17:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:11
            speed: 100
        FastEthernet0/18:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:12
            speed: 10
        FastEthernet0/19:
            description: Reserved Printer
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:13
            speed: 10
        FastEthernet0/2:
            description: RESERVED-END USERS
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:02
            speed: 10
        FastEthernet0/20:
            description: Reserved Printer
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:14
            speed: 10
        FastEthernet0/21:
            description: RANGE MEMBER CHANNEL GRP1(NETAPP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:15
            speed: 100
        FastEthernet0/22:
            description: RANGE MEMBER CHANNEL GRP1(NETAPP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:16
            speed: 100
        FastEthernet0/23:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:17
            speed: 100
        FastEthernet0/24:
            description: CAPWAPP FLEXConnect
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:18
            speed: 100
        FastEthernet0/3:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:03
            speed: 100
        FastEthernet0/4:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:04
            speed: 100
        FastEthernet0/5:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:05
            speed: 10
        FastEthernet0/6:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:06
            speed: 10
        FastEthernet0/7:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:07
            speed: 100
        FastEthernet0/8:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:08
            speed: 100
        FastEthernet0/9:
            description: RESERVED-END USERS
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:09
            speed: 100
        GigabitEthernet0/1:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:19
            speed: 1000
        GigabitEthernet0/2:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:1A
            speed: 10
        Port-channel1:
            description: PORT-CHANNEL1 (STORAGE_NETAPP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:16
            speed: 200
        Vlan1:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:40
            speed: 1000
        Vlan199:
            description: VLAN MANAGEMENT
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:42
            speed: 1000
        Vlan2:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:51:3F:4B:41
            speed: 1000
    napalm_interfaces_ip:
        Vlan199:
            ipv4:
                10.15.99.8:
                    prefix_length: 24
    napalm_model: WS-C2960-24PC-L
    napalm_os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FOC1326Z51S
    napalm_uptime: 6250860
    napalm_vendor: Cisco
changed: false
failed: false
