get_facts:
    napalm_facts:
        fqdn: EKA-CME.victoria.local
        hostname: EKA-CME
        interface_list:
        - FastEthernet0/0
        - FastEthernet0/1
        - FastEthernet0/1.3
        model: '2811'
        os_version: 2800 Software (C2800NM-ADVENTERPRISEK9-M), Version 12.4(24)T1,
            RELEASE SOFTWARE (fc3)
        serial_number: FHK1445F2C7
        uptime: 7514220
        vendor: Cisco
    napalm_fqdn: EKA-CME.victoria.local
    napalm_hostname: EKA-CME
    napalm_interface_list:
    - FastEthernet0/0
    - FastEthernet0/1
    - FastEthernet0/1.3
    napalm_interfaces:
        FastEthernet0/0:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 68:BD:AB:8F:E8:40
            speed: 100
        FastEthernet0/1:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 68:BD:AB:8F:E8:41
            speed: 100
        FastEthernet0/1.3:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 68:BD:AB:8F:E8:41
            speed: 100
    napalm_interfaces_ip:
        FastEthernet0/0:
            ipv4:
                10.60.99.251:
                    prefix_length: 24
        FastEthernet0/1.3:
            ipv4:
                10.60.3.254:
                    prefix_length: 24
        VoIP-Null0:
            ipv6:
                FE80::6ABD:ABFF:FE8F:E840:
                    prefix_length: 10
    napalm_model: '2811'
    napalm_os_version: 2800 Software (C2800NM-ADVENTERPRISEK9-M), Version 12.4(24)T1,
        RELEASE SOFTWARE (fc3)
    napalm_serial_number: FHK1445F2C7
    napalm_uptime: 7514220
    napalm_vendor: Cisco
changed: false
failed: false
