get_facts:
    napalm_facts:
        fqdn: VIDswZQ.victoria.local
        hostname: VIDswZQ
        interface_list:
        - Vlan1
        - Vlan99
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        model: WS-C2960-24PC-L
        os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
            SOFTWARE (fc1)
        serial_number: FOC1340Z0UZ
        uptime: 1746540
        vendor: Cisco
    napalm_fqdn: VIDswZQ.victoria.local
    napalm_hostname: VIDswZQ
    napalm_interface_list:
    - Vlan1
    - Vlan99
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    napalm_interfaces:
        FastEthernet0/1:
            description: SORG_VPN
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:01
            speed: 100
        FastEthernet0/10:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:0A
            speed: 100
        FastEthernet0/11:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:0B
            speed: 10
        FastEthernet0/12:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:0C
            speed: 10
        FastEthernet0/13:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:0D
            speed: 100
        FastEthernet0/14:
            description: CCTV-Vidrul
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:0E
            speed: 100
        FastEthernet0/15:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:0F
            speed: 10
        FastEthernet0/16:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:10
            speed: 10
        FastEthernet0/17:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:11
            speed: 10
        FastEthernet0/18:
            description: CCTV-Vidrul
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:12
            speed: 100
        FastEthernet0/19:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:13
            speed: 10
        FastEthernet0/2:
            description: SORG_VPN
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:02
            speed: 100
        FastEthernet0/20:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:14
            speed: 10
        FastEthernet0/21:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:15
            speed: 100
        FastEthernet0/22:
            description: RESERVED INDUSTRIAL_FORNO
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:16
            speed: 100
        FastEthernet0/23:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:17
            speed: 100
        FastEthernet0/24:
            description: ''
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:18
            speed: 10
        FastEthernet0/3:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:03
            speed: 100
        FastEthernet0/4:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:04
            speed: 100
        FastEthernet0/5:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:05
            speed: 100
        FastEthernet0/6:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:06
            speed: 100
        FastEthernet0/7:
            description: LAP
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:07
            speed: 100
        FastEthernet0/8:
            description: AP_Regist(Vict2ndWC)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:08
            speed: 100
        FastEthernet0/9:
            description: RESERVED SIL_Industrial
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:09
            speed: 100
        GigabitEthernet0/1:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:19
            speed: 1000
        GigabitEthernet0/2:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:1A
            speed: 10
        Vlan1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:40
            speed: 1000
        Vlan99:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:27:0C:A0:9B:41
            speed: 1000
    napalm_interfaces_ip:
        Vlan99:
            ipv4:
                10.70.99.21:
                    prefix_length: 24
    napalm_model: WS-C2960-24PC-L
    napalm_os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FOC1340Z0UZ
    napalm_uptime: 1746540
    napalm_vendor: Cisco
changed: false
failed: false
