get_facts:
    napalm_facts:
        fqdn: SW_8PoE_CCC_P.Medico.victoria.local
        hostname: SW_8PoE_CCC_P.Medico
        interface_list:
        - Vlan1
        - Vlan199
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        model: WS-C2960C-8PC-L
        os_version: C2960C Software (C2960c405-UNIVERSALK9-M), Version 15.0(2)SE5,
            RELEASE SOFTWARE (fc1)
        serial_number: FOC1849Z7YM
        uptime: 2457420
        vendor: Cisco
    napalm_fqdn: SW_8PoE_CCC_P.Medico.victoria.local
    napalm_hostname: SW_8PoE_CCC_P.Medico
    napalm_interface_list:
    - Vlan1
    - Vlan199
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    napalm_interfaces:
        FastEthernet0/1:
            description: Reserved End Users SOBA
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:81
            speed: 100
        FastEthernet0/2:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:82
            speed: 10
        FastEthernet0/3:
            description: Reserved CCTV+BIO CCC
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:83
            speed: 100
        FastEthernet0/4:
            description: Reserved CCTV+BIO CCC
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:84
            speed: 10
        FastEthernet0/5:
            description: Reserved CCTV+BIO CCC
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:85
            speed: 100
        FastEthernet0/6:
            description: Reserved CCTV+BIO CCC
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:86
            speed: 100
        FastEthernet0/7:
            description: Reserved CCTV+BIO CCC
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:87
            speed: 10
        FastEthernet0/8:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:88
            speed: 10
        GigabitEthernet0/1:
            description: Reserved To Trunk
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:89
            speed: 1000
        GigabitEthernet0/2:
            description: Reserved To Trunk
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:8A
            speed: 10
        Vlan1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:C0
            speed: 1000
        Vlan199:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 3C:5E:C3:76:66:C1
            speed: 1000
    napalm_interfaces_ip:
        Vlan199:
            ipv4:
                10.90.99.16:
                    prefix_length: 24
    napalm_model: WS-C2960C-8PC-L
    napalm_os_version: C2960C Software (C2960c405-UNIVERSALK9-M), Version 15.0(2)SE5,
        RELEASE SOFTWARE (fc1)
    napalm_serial_number: FOC1849Z7YM
    napalm_uptime: 2457420
    napalm_vendor: Cisco
changed: false
failed: false
