get_facts:
    napalm_facts:
        fqdn: RT-TerraVerde-CCBL.victoria.local
        hostname: RT-TerraVerde-CCBL
        interface_list:
        - Embedded-Service-Engine0/0
        - GigabitEthernet0/0
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        - FastEthernet0/0/0
        - FastEthernet0/0/1
        - Loopback0
        model: CISCO2911/K9
        os_version: C2900 Software (C2900-UNIVERSALK9-M), Version 15.1(4)M4, RELEASE
            SOFTWARE (fc1)
        serial_number: FCZ162620H6
        uptime: 3840
        vendor: Cisco
    napalm_fqdn: RT-TerraVerde-CCBL.victoria.local
    napalm_hostname: RT-TerraVerde-CCBL
    napalm_interface_list:
    - Embedded-Service-Engine0/0
    - GigabitEthernet0/0
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    - FastEthernet0/0/0
    - FastEthernet0/0/1
    - Loopback0
    napalm_interfaces:
        Embedded-Service-Engine0/0:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:00:00:00:00:00
            speed: 10
        FastEthernet0/0/0:
            description: NERA_WAN (VIDRUL)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: F0:F7:55:A6:59:37
            speed: 100
        FastEthernet0/0/1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: F0:F7:55:A6:59:38
            speed: 100
        GigabitEthernet0/0:
            description: NERA_WAN (FUNDA)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: A4:93:4C:F3:48:30
            speed: 1000
        GigabitEthernet0/1:
            description: NERA_WAN (VIANA)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: A4:93:4C:F3:48:31
            speed: 1000
        GigabitEthernet0/2:
            description: NERA_WAN (VICTORIA)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: A4:93:4C:F3:48:32
            speed: 1000
        Loopback0:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: ''
            speed: 8000
    napalm_interfaces_ip:
        FastEthernet0/0/0:
            ipv4:
                172.31.255.49:
                    prefix_length: 30
        GigabitEthernet0/0:
            ipv4:
                172.31.255.42:
                    prefix_length: 30
        GigabitEthernet0/1:
            ipv4:
                172.31.255.30:
                    prefix_length: 30
        GigabitEthernet0/2:
            ipv4:
                172.31.255.17:
                    prefix_length: 30
        Loopback0:
            ipv4:
                2.2.2.3:
                    prefix_length: 32
    napalm_model: CISCO2911/K9
    napalm_os_version: C2900 Software (C2900-UNIVERSALK9-M), Version 15.1(4)M4, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FCZ162620H6
    napalm_uptime: 3840
    napalm_vendor: Cisco
changed: false
failed: false
