---
- name: IOS USE TEMPLATE
  connection: local 
  hosts: all
  gather_facts: no

  pre_tasks:
      - name: TAKE BACKUP BEFORE CHANGES 
        ios_config:
            provider: "{{ ios_provider }}"
            authorize: yes 
            backup: "yes" 


  roles:
#      - base
#      - tacacs
      - snmp
      - loggin
#      - netflow 
 
  post_tasks:
     - name: SAVE CONFIG 
       ios_command:
           provider: "{{ ios_provider }}"
           authorize: yes 
           commands:
               - wr
       tags: ['save']

...
