---
- name: ADD LOGGIN FILE & ASSEMBLY
  template: src=loggin.j2 dest={{ inventory_dir }}/{{ build_dir }}/04-loggin.conf
  run_once: true 
  tags: ['loggin_file']

- name: SETUP LOGGIN
  ios_config:
      authorize: yes 
      provider: "{{ ios_provider }}"
      diff_against: running
      src: loggin.j2 
  tags: ['loggin']

...
