get_facts:
    napalm_facts:
        fqdn: COBswF3.victoria.local
        hostname: COBswF3
        interface_list:
        - Vlan1
        - Vlan9
        - Vlan99
        - FastEthernet0/1
        - FastEthernet0/2
        - FastEthernet0/3
        - FastEthernet0/4
        - FastEthernet0/5
        - FastEthernet0/6
        - FastEthernet0/7
        - FastEthernet0/8
        - FastEthernet0/9
        - FastEthernet0/10
        - FastEthernet0/11
        - FastEthernet0/12
        - FastEthernet0/13
        - FastEthernet0/14
        - FastEthernet0/15
        - FastEthernet0/16
        - FastEthernet0/17
        - FastEthernet0/18
        - FastEthernet0/19
        - FastEthernet0/20
        - FastEthernet0/21
        - FastEthernet0/22
        - FastEthernet0/23
        - FastEthernet0/24
        - GigabitEthernet0/1
        - GigabitEthernet0/2
        - Port-channel1
        - Port-channel2
        - Port-channel3
        model: WS-C2960-24PC-L
        os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
            SOFTWARE (fc1)
        serial_number: FOC1329W6C5
        uptime: 21413460
        vendor: Cisco
    napalm_fqdn: COBswF3.victoria.local
    napalm_hostname: COBswF3
    napalm_interface_list:
    - Vlan1
    - Vlan9
    - Vlan99
    - FastEthernet0/1
    - FastEthernet0/2
    - FastEthernet0/3
    - FastEthernet0/4
    - FastEthernet0/5
    - FastEthernet0/6
    - FastEthernet0/7
    - FastEthernet0/8
    - FastEthernet0/9
    - FastEthernet0/10
    - FastEthernet0/11
    - FastEthernet0/12
    - FastEthernet0/13
    - FastEthernet0/14
    - FastEthernet0/15
    - FastEthernet0/16
    - FastEthernet0/17
    - FastEthernet0/18
    - FastEthernet0/19
    - FastEthernet0/20
    - FastEthernet0/21
    - FastEthernet0/22
    - FastEthernet0/23
    - FastEthernet0/24
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    - Port-channel1
    - Port-channel2
    - Port-channel3
    napalm_interfaces:
        FastEthernet0/1:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:01
            speed: 100
        FastEthernet0/10:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:0A
            speed: 10
        FastEthernet0/11:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:0B
            speed: 100
        FastEthernet0/12:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:0C
            speed: 100
        FastEthernet0/13:
            description: EtherChannel Member1 (GRPE1 NETAPP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:0D
            speed: 100
        FastEthernet0/14:
            description: LINK WIRELESS TRUNK SUMOL
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:0E
            speed: 10
        FastEthernet0/15:
            description: EtherChannel Member2 (GRPE2 NETAPP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:0F
            speed: 100
        FastEthernet0/16:
            description: EtherChannel Member2 (GRPE2 NETAPP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:10
            speed: 100
        FastEthernet0/17:
            description: EtherChannle Member3 (GRPE3 NETTAP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:11
            speed: 100
        FastEthernet0/18:
            description: EtherChannle Member3 (GRPE3 NETTAP)
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:12
            speed: 100
        FastEthernet0/19:
            description: trunk to EXI
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:13
            speed: 100
        FastEthernet0/2:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:02
            speed: 100
        FastEthernet0/20:
            description: Reserved_CCTV
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:14
            speed: 100
        FastEthernet0/21:
            description: Reserved_CCTV
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:15
            speed: 100
        FastEthernet0/22:
            description: LINK-TO-PRINTER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:16
            speed: 100
        FastEthernet0/23:
            description: trunk to EXI
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:17
            speed: 100
        FastEthernet0/24:
            description: LINK-TO-AP
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:18
            speed: 100
        FastEthernet0/3:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:03
            speed: 100
        FastEthernet0/4:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:04
            speed: 100
        FastEthernet0/5:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:05
            speed: 100
        FastEthernet0/6:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:06
            speed: 100
        FastEthernet0/7:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:07
            speed: 100
        FastEthernet0/8:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:08
            speed: 100
        FastEthernet0/9:
            description: RESERVED IPT+ENDUSER
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:09
            speed: 10
        GigabitEthernet0/1:
            description: Trunk_to_fiberSW3750X
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:19
            speed: 1000
        GigabitEthernet0/2:
            description: Trunk_To_SW_Core
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:1A
            speed: 1000
        Port-channel1:
            description: GRP1 CHANNEL_GRPE(VLAN6)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:00:00:00:00:00
            speed: 10
        Port-channel2:
            description: GRP2 CHANNEL_GRPE(VLAN6)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:00:00:00:00:00
            speed: 10
        Port-channel3:
            description: GRP3 CHANNEL_GRPE(VLAN98)
            is_enabled: true
            is_up: false
            last_flapped: -1.0
            mac_address: 00:00:00:00:00:00
            speed: 10
        Vlan1:
            description: ''
            is_enabled: false
            is_up: false
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:40
            speed: 1000
        Vlan9:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:41
            speed: 1000
        Vlan99:
            description: ''
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 00:26:98:94:90:42
            speed: 1000
    napalm_interfaces_ip:
        Vlan99:
            ipv4:
                10.40.99.5:
                    prefix_length: 24
    napalm_model: WS-C2960-24PC-L
    napalm_os_version: C2960 Software (C2960-LANBASEK9-M), Version 12.2(55)SE9, RELEASE
        SOFTWARE (fc1)
    napalm_serial_number: FOC1329W6C5
    napalm_uptime: 21413460
    napalm_vendor: Cisco
changed: false
failed: false
